product-name = "ollama-lab"
version = "0.3.2"
identifier = "org.ollamalab.tauri"

[build]
before-build-command = "bun run build"
before-dev-command = "bun run dev"
frontend-dist = "../dist"
dev-url = "http://localhost:5173"

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

[[app.windows]]
fullscreen = false
height = 600
resizable = true
title = "Ollama Lab"
width = 800
maximized = true

[app.security]
csp = ""
